#!/bin/bash
set -euo pipefail

LOGFILE=$1
OUTPUT_DIR=$2

FAILURE_VERDICTS_LINENOS=(
$(grep --text --line-number 'Testcase failed' "$LOGFILE" | cut -f 1 -d :)
)

ANNOUNCEMENTS_LINENOS_DESCENDING=(
$(grep --text --line-number '^[-][-] Testing' "$LOGFILE" | cut -f 1 -d : | tac)
)

for failure_verdict_lineno in ${FAILURE_VERDICTS_LINENOS[@]}; do
	for announcement_lineno in ${ANNOUNCEMENTS_LINENOS_DESCENDING[@]}; do
		range_len=$((failure_verdict_lineno - announcement_lineno + 1))
		if (( range_len > 1 )); then
			head -n $failure_verdict_lineno "$LOGFILE" | tail -n $range_len > "$OUTPUT_DIR"/$(basename "$LOGFILE")."$announcement_lineno"-"$failure_verdict_lineno".txt
			break
		fi
	done
done
