FROM debian:13

RUN apt update

RUN apt install -y \
	acl \
	apache2 \
	attr \
	autoconf \
	autofs \
	automake \
	bc \
	bzip2 \
	ccache \
	clang \
	clang-tools \
	cmake \
	cpio \
	curl \
	delve \
	devscripts \
	dnsutils \
	e2fsprogs \
	equivs \
	findutils \
	fuse3 \
	g++ \
	gawk \
	gdb \
	gdbserver \
	git \
	golang \
	gzip \
	init \
	inotify-tools \
	iproute2 \
	jq \
	libacl1 \
	libacl1-dev \
	libapache2-mod-wsgi-py3 \
	libasan8 \
	libattr1 \
	libattr1-dev \
	libcap-dev \
	libcap2-bin \
	libcap2-dev \
	libfuse-dev \
	libfuse2t64 \
	libfuse3-dev \
	libgtest-dev \
	libjemalloc-dev \
	libjemalloc2 \
	libsqlite3-dev \
	libssl-dev \
	libuuid1 \
	libzstd-dev \
	libzstd1 \
	lsof \
	make \
	meson \
	net-tools \
	ngrep \
	openssl \
	parallel \
	patch \
	patchelf \
	procps \
	psmisc \
	python3 \
	python3-dev \
	python3-pip \
	python3-pylibacl \
	python3-requests \
	python3-setuptools \
	python3-xattr \
	rr \
	rsync \
	rsyslog \
	s3cmd \
	sqlite3 \
	strace \
	sudo \
	unzip \
	uuid-dev \
	valgrind \
	varnish \
	vim \
	wget \
	xfsprogs \
	zlib1g \
	zlib1g-dev \
	zstd \
	;

RUN \
	PY_VER=3.13 \
	&& python3 -m site --user-site | grep -F /root/.local/lib/python$PY_VER/site-packages \
	&& mkdir -p /root/.local/lib/python$PY_VER/site-packages \
	&& git clone https://github.com/google/gtest-parallel /root/.local/lib/python$PY_VER/site-packages/gtest-parallel \
	&& mkdir -p /usr/local/bin \
	&& ln -sv /root/.local/lib/python$PY_VER/site-packages/gtest-parallel/gtest-parallel /usr/local/bin/

# Create the sftnight user
RUN useradd -m -s /bin/bash sftnight
RUN echo '%sftnight ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

RUN mkdir -p /etc/udev && echo children_max=1 >> /etc/udev/udev.conf

RUN echo user_allow_other >> /etc/fuse.conf

RUN sed -i /etc/autofs.conf -e 's/^#logging.*/logging=debug/'

# We definitely don't need /tmp wiping mid-job
# Mask because "disable" fails.
RUN systemctl mask systemd-tmpfiles-clean.timer

RUN systemctl disable apt-daily.timer
RUN systemctl disable apt-daily-upgrade.timer

# https://github.com/sudo-project/sudo/issues/173
RUN echo Defaults rlimit_core=default >> /etc/sudoers

# Make a working build env for rr development
RUN apt install -y \
	capnproto \
	libcapnp-dev \
	lldb \
	python3-pexpect \
	python3-rpm \
	;
RUN apt install -y \
	rpm \
	;
